# Generated by Django 5.0.7 on 2024-08-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrequest',
            name='receiver',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
